### ISSUE TITLE
Storage class as a setting

### ISSUE THREAD

**Issue by smcoll** [jazzband/silk#202]
It would make sense to me that the file storage class could be selected as a configuration, especially since many deployments these day are on ephemeral file systems.

We could set `storage`, something like this (untested):

```
from django.core.files.storage import get_storage_class
from django.conf import settings

storage_class = getattr(settings, 'SILKY_STORAGE_CLASS', 'silk.models.ProfilerResultStorage')
silky_storage = get_storage_class(storage_class)()

class Request(models.Model):
    # [...]
    prof_file = FileField(null=True, storage=silky_storage)
```

**Comment by avelis** [comment]
@smcoll If you have time to make a PR with this change I can take a look and merge it in.
