### ISSUE TITLE
Visualization not visible

### ISSUE THREAD

**Issue by physicalattraction** [jazzband/silk#205]
When creating a profile, the visualization is not shown in the browser. I have installed graphviz using HomeBrew.

<img width="973" alt="screen shot 2017-08-03 at 15 54 25" src="https://user-images.githubusercontent.com/7287514/28925117-35575292-7864-11e7-80ea-b6d9ac3dff1d.png">

**Comment by danielbradburn** [comment]
A couple of things you can check:

* Are you using the latest version from github? The pypi version doesn't contain the graph visualization.
* Do you set `SILKY_PYTHON_PROFILER_BINARY = True`?
* Is your `MEDIA_ROOT` set to a valid path? This is where the cprofile dumps will be stored.

**Comment by physicalattraction** [comment]
Thanks for your quick feedback. In fact, I did not use the latest version from github, but used pip to install version 1.0.0. I did set `SILKY_PYTHON_PROFILER_BINARY = True` and I also manually changed the profile path: `SILKY_PYTHON_PROFILER_RESULT_PATH = BASE_DIR.child('tmp', 'profiles')`.

When can the latest version be expected in pip?

**Comment by danielbradburn** [comment]
There is another issue about making a new release https://github.com/jazzband/silk/issues/187. Perhaps you could ask there what the status is.
