### ISSUE TITLE
Bad alignment in profile table

### ISSUE THREAD

**Issue by physicalattraction** [jazzband/silk#206]
The profile lines are not neatly tabulated, all lines are centered on the screen. This makes it very hard to read the numbers properly.

<img width="973" alt="screen shot 2017-08-03 at 15 54 25" src="https://user-images.githubusercontent.com/7287514/28925179-653d043e-7864-11e7-9053-242c68c3fc9c.png">

**Comment by avelis** [comment]
@physicalattraction I know we need a release but have you tried the latest from master? I think this was addressed via a CSS tweak.

**Comment by physicalattraction** [comment]
@avelis: Thanks for your reply. I didn't try it from the latest master, I didn't know there were differences between them. Good to hear that is has been solved already, this issue can be closed then.
