### ISSUE TITLE
No end_time for any captured request

### ISSUE THREAD

**Issue by hashemian** [jazzband/silk#213]
I had setup silk on my dev server and it was working as expected. But recently none of the requests shown there has any time information. They all look like [this link](https://ibb.co/fDcMpQ).

I checked the `silk_request` table, and none of the queries have `end_time` column filled. Any idea how I can figure out what's going on?

Thanks a lot

**Comment by linked** [comment]
I have the same issue when I enable SILK_PYTHON_PROFILER_BINARY; disabling the binary profiler fixes the timing issue (but obviously also disables binary profiling, which I need working)

**Comment by hashemian** [comment]
You are right. When I set the `SILK_PYTHON_PROFILER_BINARY` to `False` it works again, but not otherwise.

**Comment by danielbradburn** [comment]
I think this is related to silk being unable to store the binary profile files. I normally put this in my ``settings.py`` to ensure that the .prof files can be correctly saved:

```!python
SILKY_PYTHON_PROFILER_BINARY = True
SILKY_PYTHON_PROFILER_RESULT_PATH = os.path.join(BASE_DIR, '.profiles')
with contextlib.suppress(OSError):
    os.makedirs(SILKY_PYTHON_PROFILER_RESULT_PATH)
```

It would be nice if silk warned you when unable to save the files, however perhaps you can try this to work around the issue?

**Comment by hashemian** [comment]
You are right. The problem was that Silk could not access the path I had specified. Permission problem. It would be very helpful if somehow we could get a more helpful error message, like HTTP 500.

Thanks a lot.
