### ISSUE TITLE
The dashboard shows views with no queries as most time taken in database

### ISSUE THREAD

**Issue by hvdklauw** [jazzband/silk#217]
Database: Postgresql.

It seems the views without queries take the most time because it's sorting on a nullable field/aggregation which in postgresql come first when sorting decending.

I don't think django orm supports the "NULLS FIRST" / "NULLS LAST" options, so the nulls should probably be filtered as they are irrelevant for the specific part of the dashboard.

**Comment by avelis** [comment]
@hvdklauw If you can make a PR contributing to optimize this that would be great!
