### ISSUE TITLE
Organise cProfile output as a sortable, more organised table.

### ISSUE THREAD

**Issue by mtford90** [jazzband/silk#33]
It's currently just text dumped into a code block. Would be nice if this could be organised as a HTML table and possibly change the sorting etc (i.e. only sorted by cumulative atm)

**Comment by danielbradburn** [comment]
I think the changes in https://github.com/jazzband/silk/pull/200 should fix this, can it be closed now?

**Comment by avelis** [comment]
@danielbradburn Yes It can.
